window.kindergartenData = {
    "classes": [
        {
            "id": "cl-1781591664919",
            "name": "Koala",
            "branch": "HimLam Campus",
            "image": "images/img_1784023347141.jpg"
        },
        {
            "id": "cl-1781720238526",
            "name": "Koala 1",
            "branch": "VDT Campus",
            "image": "images/img_1781594482576.jpg"
        },
        {
            "id": "cl-1782789219228",
            "name": "Panda 1",
            "branch": "VDT Campus",
            "image": "images/img_1781594622803.jpg"
        },
        {
            "id": "cl-1782789297650",
            "name": "Dolphin 1",
            "branch": "VDT Campus",
            "image": "images/img_1781594690908.jpg"
        },
        {
            "id": "cl-1782789307731",
            "name": "Giraffe 1",
            "branch": "VDT Campus",
            "image": "images/img_1781594600632.jpg"
        },
        {
            "id": "cl-17828882069170.18700691993405727",
            "name": "Panda",
            "branch": "HimLam Campus",
            "image": "images/img_1784023782557.jpg"
        },
        {
            "id": "cl-17828882069170.6064161715832719",
            "name": "Dolphin",
            "branch": "HimLam Campus",
            "image": "images/img_1784023809329.jpg"
        },
        {
            "id": "cl-17828882069180.0948946666514725",
            "name": "Giraffe",
            "branch": "HimLam Campus",
            "image": "images/img_1784023819213.jpg"
        },
        {
            "id": "cl-1783936323423",
            "name": "Koala VD",
            "branch": "VDT Campus",
            "image": "images/icon/koala.png"
        }
    ],
    "students": [
        {
            "id": "st-1781152929814",
            "name": "Trần Quốc Bảo",
            "nickname": "Bảo Bảo",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/img_1781166511024.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-1781164535551",
            "name": "Huỳnh Trần Thiên An",
            "nickname": "suboi",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/img_1782793984362.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1781164837815",
            "name": "Bùi Thanh Vân",
            "nickname": "Vân Vân",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/img_1782793969341.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1781580563385",
            "name": "Trần Phương Linh",
            "nickname": "Clouis",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/img_1781580557563.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-1781585644915",
            "name": "Đoàn Nguyễn Minh Khôi",
            "nickname": "Bơ",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/img_1782793953563.jpg",
            "sound": "sounds/audio_1781585637216.mp3",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069160.8116195857464572",
            "name": "Nguyễn Minh Triết",
            "nickname": "Bin",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069160.6090958715977649",
            "name": "Trần Ngọc Phương Anh",
            "nickname": "Su",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069160.9915244318632419",
            "name": "Lê Hoàng Nam",
            "nickname": "Bắp",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069160.6263371037484117",
            "name": "Phạm Minh Khang",
            "nickname": "Kẹo",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069160.3233546988278403",
            "name": "Vũ Hoàng Yến",
            "nickname": "Thỏ",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069170.2329035518621031",
            "name": "Phan Quốc Bảo",
            "nickname": "Gấu",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069170.5069646792541761",
            "name": "Đặng Thùy Dương",
            "nickname": "Mây",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069170.778766331865599",
            "name": "Bùi Gia Huy",
            "nickname": "Sóc",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069170.21851439010491547",
            "name": "Ngô Khánh Linh",
            "nickname": "Bống",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069170.4296262277467776",
            "name": "Đỗ Minh Đức",
            "nickname": "Tít",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069180.059563482387681055",
            "name": "Đặng Anh Tuấn",
            "nickname": "Cua",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069180.5454474524474243",
            "name": "Bùi Minh Thư",
            "nickname": "Nấm",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069180.3927157111873478",
            "name": "Ngô Hoàng Long",
            "nickname": "Rồng",
            "branch": "VDT Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069180.6334966685360075",
            "name": "Đỗ Thục Anh",
            "nickname": "Xoài",
            "branch": "VDT Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069180.45301238142754374",
            "name": "Nguyễn Phúc Thịnh",
            "nickname": "Bo",
            "branch": "VDT Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069190.5653587883276029",
            "name": "Trần Gia Linh",
            "nickname": "Kem",
            "branch": "VDT Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17828882069190.8265378725278503",
            "name": "Lê Minh Quân",
            "nickname": "Nghé",
            "branch": "VDT Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-17828882069190.20954799059755058",
            "name": "Phạm Bảo Ngọc",
            "nickname": "Bơ",
            "branch": "VDT Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17830689211060.7360725274956346",
            "name": "Trần Quốc Bảo",
            "nickname": "Bảo",
            "branch": "VDT Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": true,
            "busRoute": ""
        },
        {
            "id": "st-1784025132189",
            "name": "AN HI",
            "nickname": "AN HI",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "sounds/audio_1784025950462.mp3",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1784025239804",
            "name": "THANH KHÔI",
            "nickname": "SUN",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1784025252580",
            "name": "THANH LONG",
            "nickname": "THANH LONG",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1784025268124",
            "name": "UYÊN MY",
            "nickname": "CLARA",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1784025285829",
            "name": "THẢO NHI",
            "nickname": "HANI",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1784025312092",
            "name": "LÊ QUANG",
            "nickname": "TIN",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1784025328876",
            "name": "NHẬT TRÀ",
            "nickname": "SURI",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-1784025349892",
            "name": "ÁNH TUYỀN",
            "nickname": "ÁNH TUYỀN",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "sounds/audio_1784025963986.mp3",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.6010794691101361",
            "name": "TRẦN CƯỜNG",
            "nickname": "BIN",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.49277329150244",
            "name": "NHÃ ĐÌNH",
            "nickname": "NA",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.8802236469028762",
            "name": "HẢI ĐÔNG",
            "nickname": "XOÀI",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.1778547885787667",
            "name": "KHÁNH HƯNG",
            "nickname": "GẤU",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.5604134592245689",
            "name": "CHẤN HƯNG",
            "nickname": "BI",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.5459039418995398",
            "name": "MINH HY",
            "nickname": "MÍA",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.8538922845453933",
            "name": "HẠ LINH",
            "nickname": "MOON",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.37570470550301516",
            "name": "AN MINH",
            "nickname": "FINN",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.851506838349683",
            "name": "KHANG NHI",
            "nickname": "CÚN",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.4788134493734848",
            "name": "HOÀNG PHÚ",
            "nickname": "DOLLAR",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.05319871555971467",
            "name": "TRẦN PHƯỚC",
            "nickname": "BO",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.37654005702340354",
            "name": "ANH THƯ",
            "nickname": "MIA",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.13974092690003725",
            "name": "KHẢI UY",
            "nickname": "SỬU NHI",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114130.3172280048374988",
            "name": "HẠ VY",
            "nickname": "DỪA",
            "branch": "HimLam Campus",
            "class": "Koala",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.030792748765159583",
            "name": "THIÊN AN",
            "nickname": "TÁO",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.0849556741665024",
            "name": "NHẬT ANH",
            "nickname": "CHLOE",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.35123443470949667",
            "name": "SƠN CA",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.12142746117762515",
            "name": "YÊN CHI",
            "nickname": "CÀ RỐT",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.8255049349433324",
            "name": "QUỐC CƯỜNG",
            "nickname": "TÔ GÀ",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.8263338049867489",
            "name": "MINH ĐAN",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.32556675628412923",
            "name": "BÁ HIẾN",
            "nickname": "LUIS",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.13204375945783042",
            "name": "NHÃ KHUÊ",
            "nickname": "BÉ BÉ",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.6402788416535389",
            "name": "ANH MINH",
            "nickname": "TOMMY",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.8608214640787811",
            "name": "KHÔI MINH",
            "nickname": "KHOAI TÂY",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.25831096896197026",
            "name": "TRÀ MY",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.061751505590124434",
            "name": "CAO PHONG",
            "nickname": "PHILIP",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.3422849394592342",
            "name": "LAN PHƯƠNG",
            "nickname": "BỐI BỐI",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.481723182189536",
            "name": "UY VŨ",
            "nickname": "PETER",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.8051842800670452",
            "name": "HOÀNG VY",
            "nickname": "LYNN",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.2587263115719012",
            "name": " LOIY ISHAQ JABARIYOUNIS",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Panda",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.238423121923385",
            "name": "TUẤN ANH",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.3719008469175311",
            "name": "NGUYỄN DUY ANH",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.023722615258672364",
            "name": "TRẦN DUY ANH",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.5753897456260373",
            "name": "HỒNG LĨNH",
            "nickname": "LINCOLN",
            "branch": "HimLam Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.7122900536545401",
            "name": "UYÊN NHI",
            "nickname": "SU KEM",
            "branch": "HimLam Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.0997477131709229",
            "name": "TRÚC PHƯƠNG",
            "nickname": "MILAN",
            "branch": "HimLam Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.43126657512860855",
            "name": "MINH TÂM",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.787781832994036",
            "name": "MINH THƯ",
            "nickname": "ZỊTT",
            "branch": "HimLam Campus",
            "class": "Dolphin",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.567508970839476",
            "name": "LINH ĐAN",
            "nickname": "ALICE",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.8051740724163569",
            "name": " PHÚC ĐẠT ",
            "nickname": "CÀ RI",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.5922711671626126",
            "name": "GIA DĨNH",
            "nickname": "HENRY",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114140.9323430846618043",
            "name": "MẠNH HÙNG",
            "nickname": "",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.564468619991658",
            "name": "MINH HƯNG",
            "nickname": "ĐÔ",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.3523903268767382",
            "name": "QUỐC HUY",
            "nickname": "SUBIN",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.7576146456606846",
            "name": "TUỆ LÂM",
            "nickname": "MỸ DÂN",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.5895135233262658",
            "name": "MINH NHẬT",
            "nickname": "MÈO RI",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.6250329142504016",
            "name": "ĐĂNG NHẬT ",
            "nickname": "BẮP",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.42757943675803534",
            "name": "ANH QUÂN",
            "nickname": "OSCAR",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.9014271611257882",
            "name": "MINH QUÂN",
            "nickname": "TOPAS",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.7586281949393122",
            "name": "NHẬT QUANG",
            "nickname": "BEN",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.823506869298087",
            "name": "LÊ QUÍ ",
            "nickname": "BÉ BA",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.6063003199677947",
            "name": "LÊ QUỲNH",
            "nickname": "BÉ TƯ",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.9698565900678214",
            "name": "MAI VÂN",
            "nickname": "MÂY",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        },
        {
            "id": "st-17840261114150.703521620105461",
            "name": "THIÊN VŨ",
            "nickname": "FIN FIN",
            "branch": "HimLam Campus",
            "class": "Giraffe",
            "image": "images/user.jpg",
            "sound": "",
            "isBus": false,
            "busRoute": ""
        }
    ],
    "branches": [
        "TanQuy Campus",
        "HimLam Campus",
        "VDT Campus"
    ]
};